Baseline setup
TimeEscaper/social_nav_baselines pull request #1
Opened 2022-12-27 11:04 UTC by AleksandrKashirin

MPC and DWA planners was added as a baseline setup

2023-01-15 23:27 UTC, TimeEscaper requested changes
Я бы предложил сразу все передалть под более общий вид архитектуры. Основные пойнты такие:

1) Сделать для всех контроллеров более-менее идеинообразный интерфейс. Например, что-то типа такого:
```
class Controller
    ...

controller = Controller()
...

control, info = controller.step(state, observation)
```

Здесь state - условно состояние робота, observation - позиции пешеходов задетекченных например; control соответственно это управления, info - словарь, в котором может всякая дополнительная инфа для визуализации содеражться, те же позиции пешеходов предсказанные, горизон позиций из mpc и т.д.

Соответственно, кажется что у тебя должны быть два таких контроллера - для MPC и для DWA. У MPC либо динамика будет как отдельный аргумент, либо просто два подкласса, у DWA - два подкласса.

2) По сути у нас все скрипты на все методы тут работают с одним типом симуляции, поэтому стоит здесь если получится сделать один скрипт для запуска, который будет просто принимать конфиг, и создавать нужные классы. Для визуализации какие-то специфичные для методов вещи можно добавлять if-ами просто.

2023-01-15 23:27 UTC, TimeEscaper commented on planners/dwa/dwa.py
> +    p_peds_k_1 = p_peds_k
По идее если ты так сделаешь, то у тебя перетрется оригинальная переменная p_peds_k, поскольку ты там потом делаешь присваивание через p_peds_k[:]. Если тебе нужно такое поведение, то лучше это в комментах написать, если нет, то поправить.

2023-01-15 23:27 UTC, TimeEscaper commented on planners/dwa/dwa.py
> +               ped_dect_range,
Опечатка в dect -> detc наверное? Но лучше тогда det назвать

2023-01-15 23:27 UTC, TimeEscaper commented on planners/dwa/dwa.py
> +    v_range = np.arange(config['lb'][0], config['ub']
По поводу вот границ в конфиге - возможно удобнее будет сделать не два вектора ub и lb на все управляющие воздействия, а отдельные пары на кажде из воздействий, типа v_bounds, w_bounds и др.
Но в целом на твое усмотрение.

2023-01-15 23:27 UTC, TimeEscaper commented on planners/dwa/dwa.py
> +    if 0 not in v_range:
Не совсем понял для чего такая проверка

2023-01-15 23:27 UTC, TimeEscaper commented on planners/dwa/dwa.py
> +    file_name = os.path.basename(__file__)
Для работы с путями советую на будущее использовать встроенный модуль pathlib - там красивее и удобнее работа получается

2023-01-15 23:27 UTC, TimeEscaper commented on planners/dwa/dwa.py
> +    with open(rf'{config_path}/{file_name}_config.yaml') as f:
Я думаю лучше сделать по-другому - просто подавать путь к конфигу на вход скрипту. Парсить аргументы скрипта можно либо через встроенный модуль argparse, либо через либу fire, с ней это ещё удобнее.

2023-01-15 23:27 UTC, TimeEscaper commented on planners/dwa/dwa.py
> +            cur_dist_to_goal = math.sqrt(
Лучше для единообразия все из numpy использовать

2023-01-15 23:27 UTC, TimeEscaper commented on planners/dwa/dwa.py
> +            for k in range(n_horizon):
В идеале, хотелось бы чтобы пропагейшн пешеходов тоже был внутри контроллера именно, а не в main-е. Для отрисовки можно будет просто их возвращать как дополнительную информацию от контроллера.

2023-01-15 23:27 UTC, TimeEscaper commented on planners/dwa/dwa_orig_cost.py
> +def propagate_all_pedestrians(p_peds_k: np.ndarray,
Хотелось бы обернуть оба DWA-контроллера в один класс. Если не получится полностью все объединить в один класс, то сделать базовый класс, туда добавить все общие методы, типа этого, который просто дублируется, и уже потом от него унаследовать два неопсредственно класса с контроллерами.

2023-01-15 23:27 UTC, TimeEscaper commented on planners/dwa/dwa_orig_cost.py
> +def create_sim(p_rob_init: np.ndarray,
В иделе конечно бы сделать так: у нас будет один скрипт, который будет просто на вход принимать тип контроллера и конфиг, и уже потом просто создавать нужные классы и запускать вот этот сценарий в симулации с пустым миром. Если так не получится сделать, то можно create_sim в utils вынести.

2023-01-15 23:27 UTC, TimeEscaper commented on planners/dwa/dwa_orig_cost.py
> +    # посчитаем допустимые скорости для движения
Лучше все на английском писать

2023-01-15 23:27 UTC, TimeEscaper commented on planners/dwa/configs/dwa_config.yaml
> +# Robot Model: Unicycle Model with State Vector: [x, y, phi]
Надо проверить, есть ли тут неиспользуемые параметры

2023-01-15 23:27 UTC, TimeEscaper commented on planners/dwa/configs/dwa_orig_cost_config.yaml
> +annotation_offset: [0, 0.2]             # Offset for annotation: [x, y]
Это для твоей визуализации на matplotlib?

2023-01-15 23:27 UTC, TimeEscaper commented on planners/mpc/mpc.py
> +        self._Q = Q
Тут надо бы убрать члены из self, которые в явном виде не используются в дальнейшем в классе. То есть условно говоря self._mpc нам точно нужен, а ряд других членов, особенно которые являются переменными из casadi, можно убрать из self (ссылки на них все равно будут в графе вычислений). Я в коде для контроллера из репозитория для tracer-а так сделал, вроде бы все ок с этим.

2023-01-15 23:27 UTC, TimeEscaper commented on planners/mpc/mpc.py
> +        self._mpc.bounds['lower', '_x', 'v'] = self._lb[0]
Про bounds тот же самый опциональный коммент, который был в dwa.

2023-01-15 23:27 UTC, TimeEscaper commented on planners/mpc/mpc_unicycle.py
> +    def propagate_all_pedestrians(self,
Этот метод наверное стоит в какой-нибудь utils-модуль вынести тоже. В идеале для него можно сделать отдельный класс базовый, его назвать как-то PedestrianPredictor, и один из его наследников - вот такой предиктор на forward velocity propagation.

2023-01-15 23:27 UTC, TimeEscaper commented on planners/mpc/mpc_unicycle.py
> +            x_pred = controller._mpc.data.prediction(('_x', 'x'))[0]
Здесь та же идея, всю логику с предиктом пешеходов тоже лучше вставить в DoMPCController, и возвращать вот эту траекторию как дополнительный выход метода.

2023-01-15 23:27 UTC, TimeEscaper commented on planners/mpc/mpc_unicycle.py
> +    robot_model = UnicycleRobotModel(initial_pose=p_rob_init,
Модель робота тоже лучше вынести в параметры, и соответственно чтобы класс DoMPCController тоже был один для них двух в идеале.

2023-01-24 14:28 UTC, AleksandrKashirin commented on planners/dwa/dwa.py
> +    if 0 not in v_range:
Это нужно для того чтобы 100% добавить возможность роботу стоят на месте и ничего не делать. Иначе можем оказаться в ситуации, когда робот просто будет кружить по кругу, как это происходит с примерами из ютуба.

2023-01-24 14:32 UTC, AleksandrKashirin commented on planners/dwa/dwa.py
> +    p_peds_k_1 = p_peds_k
Изменил с shallow copy на deep copy во всех используемых методах.

2023-01-24 14:32 UTC, AleksandrKashirin commented on planners/dwa/dwa.py
> +               ped_dect_range,
Поменял

2023-01-24 14:33 UTC, AleksandrKashirin commented on planners/dwa/dwa.py
> +    file_name = os.path.basename(__file__)
Переделать этот код или на будущее юзать pathlib?

2023-01-24 14:44 UTC, AleksandrKashirin commented on planners/dwa/dwa.py
> +            cur_dist_to_goal = math.sqrt(
Заменил, убрал

2023-01-24 14:46 UTC, AleksandrKashirin commented on planners/dwa/configs/dwa_orig_cost_config.yaml
> +annotation_offset: [0, 0.2]             # Offset for annotation: [x, y]
да

2023-01-24 14:47 UTC, AleksandrKashirin commented on planners/dwa/configs/dwa_config.yaml
> +# Robot Model: Unicycle Model with State Vector: [x, y, phi]
Нет, я вроде все неиспользуемое убирал

2023-01-24 14:47 UTC, AleksandrKashirin commented on planners/mpc/mpc.py
> +        self._Q = Q
У меня чето не работало, когда я так настраивал МПС, но ща чекнем

2023-02-07 12:31 UTC, TimeEscaper requested changes
Мы близки к завершению, осталось вот только обсудить тот момент с гоуст педестрианами, я подумаю как это лучше сделать,  ну и пару мелких правок.

2023-02-07 12:31 UTC, TimeEscaper commented on configs/mpc_config.yaml
> +ped_dect_range: 4                          # Pedestrian detector max range, [m]
ped_detc?

2023-02-07 12:31 UTC, TimeEscaper commented on core/controllers/_controller.py
> +                 state_dummy_ped: List[float],
По идее у нас могут быть контроллеры, которым этот думми пед не нужен (например DDP). Но пока так можно оставить, переделаем потом.

2023-02-07 12:31 UTC, TimeEscaper commented on core/controllers/_dwa.py
> +        if 0 not in w_range:
Возможно стоит на такие вот моменты добавлять комментарии небольшие, чтобы не забыть и другим было если что сразу понятно

2023-02-07 12:31 UTC, TimeEscaper commented on core/controllers/_dwa.py
> +                  ground_truth_pedestrians_state: np.ndarray) -> np.ndarray:
Для ground_truth я думаю можно gt просто писать в будущем, вроде бы довольно распространенное сокращение.

2023-02-07 12:31 UTC, TimeEscaper commented on core/controllers/_dwa.py
> +                         goal,
Можно в принципе указать в комментах что мы тут референсный дирекшн не юзаем. Тогда кажется эти функции с get_ref_direction особо не нужны в базовом классе.

2023-02-07 12:31 UTC, TimeEscaper commented on core/controllers/_mpc.py
> +            self._mpc.bounds["lower", "_u", "u_alpha"] = -3
Лучше оставить коммент наверное, почему мы тут константу просто взяли, типа что основные ограничения у нас на скорость идут.

2023-02-07 12:31 UTC, TimeEscaper commented on core/predictors/_predictor.py
> +    def dt(self) -> float:
Проперти как-то странно дублируется

2023-02-07 12:31 UTC, TimeEscaper commented on core/visualizer/_visualizer.py
> +class Visualizer():
Можно указать Matplotlib initializer)

2023-02-07 12:31 UTC, TimeEscaper commented on examples/dwa.py
> +                    detected_pedestrian_indices = simulator.current_state.sensors['pedestrian_detector'].reading.pedestrians.keys()
Эту бы логику тоже внутрь контроллера засунуть. Я подумаю как это лучше сделать.

2023-02-07 12:31 UTC, TimeEscaper commented on setup.py
> +setup(
Пока он в принципе не нужен, но пусть будет для начала

2023-02-07 12:38 UTC, AleksandrKashirin commented on configs/mpc_config.yaml
> +ped_dect_range: 4                          # Pedestrian detector max range, [m]
fixed

2023-02-07 12:39 UTC, AleksandrKashirin commented on core/controllers/_controller.py
> +                 state_dummy_ped: List[float],
ok

2023-02-07 12:40 UTC, AleksandrKashirin commented on core/controllers/_dwa.py
> +        if 0 not in w_range:
Добавил

2023-02-07 12:41 UTC, AleksandrKashirin commented on core/controllers/_dwa.py
> +                  ground_truth_pedestrians_state: np.ndarray) -> np.ndarray:
Я вообще решил в классах, поскольку они скрыты от пользователя максимально подробные имена переменным давать

2023-02-07 12:44 UTC, AleksandrKashirin commented on core/controllers/_dwa.py
> +                         goal,
Решено пока оставить, так как может пригодится в DDP. Если не нужен будет в DDP, то потом перенесем только в MPC

2023-02-07 12:45 UTC, AleksandrKashirin commented on core/controllers/_mpc.py
> +            self._mpc.bounds["lower", "_u", "u_alpha"] = -3
Done

2023-02-07 12:49 UTC, AleksandrKashirin commented on core/predictors/_predictor.py
> +    def dt(self) -> float:
Fixed

2023-02-07 12:51 UTC, AleksandrKashirin commented on examples/dwa.py
> +                    detected_pedestrian_indices = simulator.current_state.sensors['pedestrian_detector'].reading.pedestrians.keys()
ok

2023-02-07 12:51 UTC, AleksandrKashirin commented on setup.py
> +setup(
Без него не заводится же

2023-05-04 13:19 UTC, merged